# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='从事的职业')),
            ],
            options={
                'verbose_name': '岗位列表',
                'verbose_name_plural': '岗位列表',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_a', models.CharField(max_length=20, verbose_name='答案A')),
                ('answer_b', models.CharField(max_length=20, verbose_name='答案B')),
                ('answer_c', models.CharField(max_length=20, verbose_name='答案C')),
            ],
            options={
                'verbose_name': '测试选项',
                'verbose_name_plural': '测试选项',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.CharField(max_length=100, verbose_name='问题')),
                ('job_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Job', verbose_name='所属岗位')),
            ],
            options={
                'verbose_name': '测试问题',
                'verbose_name_plural': '测试问题',
            },
        ),
        migrations.AddField(
            model_name='option',
            name='question_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Question', verbose_name='所属问题'),
        ),
    ]
